name: ${project.name}
version: ${project.version}
main: tech.bosstop.bloodworld.BloodWorld
api-version: 1.20
author: "Sir_Blob_"

commands:
  bloodworld:
    description: "BloodWorld command"
    usage: /bw [reload]
    aliases: [bw]